### ISSUE TITLE
Falta link a la guia

### ISSUE THREAD

**Issue by hdf1996** [FreeCodeCampBA/freecodecampba.github.io#10]
# Contexto
En el diseño figura:
![fcc redesign figma 1](https://user-images.githubusercontent.com/1130309/29854301-663fb7b6-8d1b-11e7-8970-54e667a7c95e.png)

En el codigo actual:
![localhost 3000 home 1](https://user-images.githubusercontent.com/1130309/29854303-67d82194-8d1b-11e7-914a-13500abeaca4.png)

# Objetivo
Crear modificar el texto correspondiente para que sea un link apuntando a https://github.com/FreeCodeCampBA/quick-start.
Asegurarse que el estilo del link coincida con el del diseño

**Comment by hdf1996** [comment]
Falta confirmacion del copy @nhsz

**Comment by nhsz** [comment]
Ver textos en [#13](https://github.com/FreeCodeCampBA/freecodecampba.github.io/issues/13) y [#14](https://github.com/FreeCodeCampBA/freecodecampba.github.io/issues/14)
