### ISSUE TITLE
Falta link a freecodecamp

### ISSUE THREAD

**Issue by hdf1996** [FreeCodeCampBA/freecodecampba.github.io#11]
# Contexto
Similar a #10.

En el diseño figura
![fcc redesign figma 2](https://user-images.githubusercontent.com/1130309/29854377-e85da24e-8d1b-11e7-93dd-8deb73d1fc60.png)

Y en el codigo actual:
![localhost 3000 home 2](https://user-images.githubusercontent.com/1130309/29854382-ffdec948-8d1b-11e7-8ed0-c6efdac8f7a6.png)

# Objetivo
lograr que el texto correspondiente sea un link https://www.freecodecamp.org/ . Respetar formato y colores del diseño, ademas de que estos deben coincidir con los usados en #10

**Comment by hdf1996** [comment]
Falta confirmacion del copy @nhsz

**Comment by nhsz** [comment]
Ver textos en [#13](https://github.com/FreeCodeCampBA/freecodecampba.github.io/issues/13) y [#14](https://github.com/FreeCodeCampBA/freecodecampba.github.io/issues/14)
