### ISSUE TITLE
Agregar favicon

### ISSUE THREAD

**Issue by nhsz** [FreeCodeCampBA/freecodecampba.github.io#2]

**Comment by nhsz** [comment]
Estaría bueno tener el logo https://github.com/FreeCodeCampBA/freecodecampba.github.io/blob/master/dist/img/logo.svg como favicon

**Comment by lndgalante** [comment]
Nico, use el mismo logo pero solo la parte de la llama ya que los favicon generators como este http://www.favicomatic.com/ comprimían mucho la imágen ya que no hay muchos pixeles y quedaba muy estrecha y por ende deformada. Dejando solo la parte de la llama quedo bien, fijate si te funciona y si te gusta así. Saludos

**Comment by nhsz** [comment]
Sip, me funciona y queda genial! 
Le doy close.
