### ISSUE TITLE
carousel de fotos de meetups pasadas 

### ISSUE THREAD

**Issue by hdf1996** [FreeCodeCampBA/freecodecampba.github.io#27]
Agregar el slider como figura en el diseño. Pensarlo de alguna forma en la que podamos agregar imagenes a futuro de forma sencilla
![fcc redesign figma](https://user-images.githubusercontent.com/1130309/30285005-f7478d14-971c-11e7-9718-2ac33ec32e3e.png)
Implementar algo de forma lo mas similar a la pagina de https://auth0.com/jobs (particularmente el area de cultura). En la pagina de auth0 utilizan https://owlcarousel2.github.io/OwlCarousel2/
![jobs auth0](https://user-images.githubusercontent.com/1130309/30285200-aa87f22e-971d-11e7-9f84-3815fdd1ab7f.png)

# NOTA:
Pueden usar imagenes de ejemplo por ahora, quedaria pendiente pedirle al resto las imagenes a mostrar (o definir si las vamos a sacar de instagram o algo asi)

**Comment by nhsz** [comment]
Ver si se puede lograr con esta lib: https://pawelgrzybek.com/siema/

**Comment by nhsz** [comment]
Si la anterior no funciona y necesitan jQuery, esta es una alternativa más liviana: http://zeptojs.com
