### ISSUE TITLE
Proximo evento frontend

### ISSUE THREAD

**Issue by hdf1996** [FreeCodeCampBA/freecodecampba.github.io#29]
Maquetar la seccion de proximos eventos. tener en cuenta que esto *solo implica el maquetado y no traerlos desde meetup.com*. Para traerlos desde meetup vamos a hacer un issue aparte porque este issue puede ser un poco complejo (es maquetar una seccion completamente nueva), y para evitar conflictos prefiero que sea implementado por partes.
![fcc redesign figma 1](https://user-images.githubusercontent.com/1130309/30285571-d13c58f0-971e-11e7-9013-598b4a88b147.png)

# COSAS IMPORTANTES:
- *los campos de texto tienen que estar en un elemento separado para que sea facil cambiarlos dinamicamente*
- *Tiene que ser posible ocultar el elemento de esta seccion sin causar estragos en el resto de los elementos, para esto aconsejo que todo lo que van a codear de esta seccion este encerrado en un elemento y apartir de ahi maqueten*
- *El boton es un link, no hace falta por ahora que apunte a una url real, pero probarlo para confirmar que vamos a poder hacerlo en el otro ticket*

**Comment by arielger** [comment]
Solved in https://github.com/FreeCodeCampBA/freecodecampba.github.io/pull/37
